Kevin/validate estimate
hab-spc/hab-ml pull request #8
Opened 2019-04-17 03:44 UTC by ktl014

SPC Image Streaming API located in `./spc/*` directory.
README is provided for usage, along with an example.

Things to review
- code refactoring for spcserver.py (how can we make it more readable, efficient, and easy to use/test)
- documentation clarity and relevancy
- Overall though, look for reproducibility

When submitting the review, please also brainstorm a cool name for this Image Streaming API.

2019-04-22 06:17 UTC, mbwibowo requested changes
This is an initial review; I could probably add more feedback but I think this is enough for now.

### (Terrible) Names: 
* SPICI (Scripps Pier In-Situ Camera Interface)
(unless there's a better word starting with Y)
* SPCATO (SPC API Transmissions On-demand) 

### General comments
* Having two different READMEs for the script is very confusing since one only gives partial information.
* The downloading can be definitely sped up by using a `ThreadPool` or something similar.
* Would it be better to submit our own PRs so we can suggest changes to all of `spcserver.py`?

Also, I propose the use of [conventional commits](https://www.conventionalcommits.org) for commit messages, because it makes commits easier to understand.

2019-04-22 06:17 UTC, mbwibowo commented on prepare_db/create_csv.py
>  DATA_DIR = '/data6/lekevin/hab-spc/phytoplankton-db'
Not really part of this PR but we should remove these hardcoded locations eventually

2019-04-22 06:17 UTC, mbwibowo commented on spc/README.md
> +1. A search parameter text file containing the start and end dates, minimum/maximum organism length, and camera choice
Might as well put examples inline here to make things easier to read/understand (no need to look in other dirs), or maybe link to the actual example

2019-04-22 06:17 UTC, mbwibowo commented on .gitignore
> +tensorboardX/*
tensorboardX directory is still in the repo even though it's empty

2019-04-22 06:17 UTC, mbwibowo commented on prepare_db/parse_csv.py
> +    def compute_imaged_volume(class_size=0.07):
This function could use some explanations

2019-04-22 06:17 UTC, mbwibowo commented on spc/spc_go.py
> +        exit(-1)
Is this function being used?

Not a fan of using `exit()` within functions, `return True/False` could be used instead by all parent functions to determine success/failure

2019-04-22 06:17 UTC, mbwibowo commented on generate_graph.py
> +    X, Y = retrieve_x_y(columns, data)
lowercase `X, Y` to be consistent

2019-04-22 06:17 UTC, mbwibowo commented on prepare_db/create_csv.py
> +    image_Data = pd.read_csv(os.path.join(data_dir, "rawdata/SPCImage_data.csv"))
Strange combo of snake_case and camelCase (same with `micro_Data`)

2019-04-22 06:17 UTC, mbwibowo commented on prepare_db/parse_csv.py
> +            if x == []:
Can be just `if not x:` when checking for emptiness

2019-04-22 06:17 UTC, mbwibowo commented on spc/examples/prorocentrum/README.md
> +This example shows you how to both download and upload images to the spc.ucsd.edu using python.
```suggestion
This example shows you how to both download and upload images to spc.ucsd.edu using python.
```

2019-04-22 06:17 UTC, mbwibowo commented on spc/examples/prorocentrum/README.md
> +Once you have images ready to be uploaded, you can create an `SPCServer` and use its method
```suggestion
Once you have images ready to be uploaded, you can create an `SPCServer` object and use its method
```

2019-04-22 06:17 UTC, mbwibowo commented on spc/spcserver.py
> +        # Log errors with label uploadsit
?

2019-04-22 06:17 UTC, mbwibowo commented on spc/README.md
> +SPCServer - Downloads and upload data to spc.ucsd.edu
```suggestion
SPCServer - Downloads and uploads data to spc.ucsd.edu
```

2019-04-22 06:17 UTC, mbwibowo commented on spc/README.md
> +Run `spc_go.py` to download images from the spc.ucsd.edu.
```suggestion
Run `spc_go.py` to download images from spc.ucsd.edu. 
```

2019-04-22 06:17 UTC, mbwibowo commented on spc/README.md
> +Create an `SPCServer` to upload images to the spc.ucsd.edu
```suggestion
Create an `SPCServer` object to upload images to spc.ucsd.edu
```

2019-04-22 06:17 UTC, mbwibowo commented on prepare_db/parse_csv.py
> +                                                    pre + 'Second'] / 60 / 60)) / 24
Odd indentation

2019-04-22 06:17 UTC, mbwibowo commented on spc/spc_go.py
> +    parser.add_argument('-d', '--download', default=False, help='Download flagging option')
This option is rather awkward. Boolean flags can be better represented with `action='store_true'`, so only the `-d` flag is required

2019-04-22 06:17 UTC, mbwibowo commented on prepare_db/parse_csv.py
> +            if lbl == []:
Can use `if not lbl` instead to check for emptiness (more Pythonic), same with next line

2019-04-22 06:17 UTC, mbwibowo commented on spc/spc_go.py
> +    if (args.search_param_file is not None) and (args.download == False) and (args.image_output_path is not None):
```suggestion
    if (args.search_param_file is not None) and not args.download and (args.image_output_path is not None):
```

2019-04-22 06:17 UTC, mbwibowo commented on spc/spc_go.py
> +    if (args.image_output_path is None) and (args.download == True):
```suggestion
    if (args.image_output_path is None) and args.download:
```

2019-04-22 06:17 UTC, mbwibowo commented on spc/spcserver.py
> +            next_page = 'empty'
Seems awkward, maybe use `next_page = None` instead?

2019-04-22 06:17 UTC, mbwibowo commented on spc/spcserver.py
> +                    url_to_open = self.inurl.format(server, next_page[21::])
Explain where 21 comes from (macros/formula, comment, etc.)

2019-04-22 06:17 UTC, mbwibowo commented on spc/examples/prorocentrum/README.md
> +    $ ./spcserver.py --search-param-file=examples/prorocentrum/time_period.txt --image-output-path=examples/prorocentrum/images --meta-output-path=examples/prorocentrum/meta_data.csv -d=True
Shouldn't this be `spc_go.py`?

It seems like it can only be run from the root directory due to all the imports, which makes this example misleading. Either put in `sys.path.append('..')` at the beginning of `spc_go.py` to allow importing from the root directory, or show that it has to be run from the root directory.

Also, `spc_go.py` does not have a shebang (`#!/usr/bin/env python`) so it won't run correctly; either add that or use `python spc_go.py` instead.

2019-04-22 06:17 UTC, mbwibowo commented on spc/spcserver.py
> +            urllib.request.urlretrieve(srcpath, destpath)
This is a really slow method for downloading images as it is done serially; a multithreaded approach should work a lot faster.

2019-04-22 21:44 UTC, skrishnan99 commented on prepare_db/create_csv.py
> +    image_Data = pd.read_csv(os.path.join(data_dir, "rawdata/SPCImage_data.csv"))
We should remove hardcoding file paths

2019-04-22 21:52 UTC, skrishnan99 approved these changes

2019-04-23 20:40 UTC, ktl014 commented on prepare_db/create_csv.py
> +    image_Data = pd.read_csv(os.path.join(data_dir, "rawdata/SPCImage_data.csv"))
@Sneha-Kondur was writing in camelCase. I'm gonna refactor to make it snake_case.
Is everyone okay with snake_case?

2019-04-23 20:42 UTC, ktl014 commented on spc/spcserver.py
> +        # Log errors with label uploadsit
typo lol

2019-04-23 20:49 UTC, ktl014 commented on spc/examples/prorocentrum/README.md
> +    $ ./spcserver.py --search-param-file=examples/prorocentrum/time_period.txt --image-output-path=examples/prorocentrum/images --meta-output-path=examples/prorocentrum/meta_data.csv -d=True
Oh I keep getting import errors like this for all files when I'm running from the terminal. What's your suggestion for this? Is the root directory gonna be everything up to hab-spc like `/data6/<NAME>/hab-spc/`?

2019-04-23 20:53 UTC, merged